### PR TITLE
Linux support v0.5.0

### PR DESCRIPTION
**Pull request by Rune580**
Naive rebase of #12  onto v0.5.0, Only a draft pr until after I test the branch

### CODE REVIEW

**Comment by Rune580** [comment]
Unless this is an existing issue, video transcoding?/imporitng? seems to fail, but otherwise everything else seems to still work

**Comment by Rune580** [comment]
Going to implement video re-encoding on linux before this PR is ready

**Comment by Rune580** [comment]
video re-encoding has been implemented, ended up needing to make `RunGuidGroup` async. Going to update the readme and then it should be ready

**Comment by Rune580** [comment]
There is a TODO in the FFmpegModule for allowing users to override the ffmpeg location, I can implement it if you want, otherwise this PR is basically good to go

**Comment by nomnomab** [comment]
Tested it and it seems to patch fine :) Will merge it in 👍

**Pull request merged**
